blankdirsetup: add auto-run of all entries in directory

diff --git a/blankdirsetup b/blankdirsetup
--- a/blankdirsetup
+++ b/blankdirsetup
@@ -1,13 +1,16 @@
 #!/bin/sh
 
 usage() {
-	echo "Usage: $0 basedir [entry]+" >&2;
+	echo "Usage: $0 basedir <all | entries [entry]+>" >&2;
 	exit 1;
 }
 if test $# -lt 2; then usage; fi;
 
 basedir="$1";
-shift;
+action="$2";
+shift 2;
+
+
 
 # oops, global variable usage?
 tryentry() {
@@ -19,13 +22,34 @@ tryentry() {
 	install --directory --owner="$owner" --group="$group" --mode="$mode" -- "$target";
 }
 
-result=0;
-for entry in "$@"; do {
-	tryentry "$entry" || {
-		e=$?;
-		echo "Warning: exit code $e creating entry $entry" >&2;
-		result=2;
-	};
-}; done;
+runarray() {
+	result=0;
+	for entry in "$@"; do {
+		tryentry "$entry" || {
+			e=$?;
+			echo "Warning: exit code $e creating entry $entry" >&2;
+			result=2;
+		};
+	}; done;
+	return $result;
+}
 
-exit $result;
+# if using "all", no other arguments are allowed.
+case "$action" in
+	all)
+		if test $# -gt 0; then {
+			echo "Error: action \"all\" does not accept arguments">&2;
+			usage;
+		}; else {
+			# try to run for each in base dir.
+			# not really sure how to catch errors in ls here
+			runarray $(ls "${basedir}");
+		}; fi;;
+	entries)
+		if test $# -lt 1; then {
+			runarray "$@";
+		}; fi;;
+	*)
+		echo "Unsupported action $action" >&2;
+		usage;
+esac;
